language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
sudo: required
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++-4.9-dev
        - g++-4.9
env: CC=clang-4.9 && CXX=clang-4.9 && LINK=gcc-4.9 && LINKXX=g++-4.9
install:
  - npm install
  - npm install nodegit --build-from-source
  - ./node_modules/.bin/mrdeveloper
script:
  - npm run test
  - npm run build
notifications:
  email:
  - ebrehault@gmail.com, ramon.nb@gmail.com, thomas.desvenain@gmail.com
