language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
install:
  - npm install
  - ./node_modules/.bin/mrdeveloper
script:
  - npm run test
  - npm run build
notifications:
  email:
  - ebrehault@gmail.com, ramon.nb@gmail.com, thomas.desvenain@gmail.com
