language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g yarn
install:
  - yarn install
  - yarn run install-self-peers
  - cd ./tests && yarn install && npm install coveralls mocha-lcov-reporter && cd ..
script:
  - yarn test
  - yarn build
after_success:
  - cd ./tests && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
  - tisto@plone.org, ebrehault@gmail.com, ramon.nb@gmail.com, sneridagh@gmail.com, thomas.desvenain@gmail.com
