language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++-4.9-dev
install:
  - npm install
  - npm install nodegit --build-from-source
  - ./node_modules/.bin/mrdeveloper
script:
  - npm run test
  - npm run build
notifications:
  email:
  - ebrehault@gmail.com, ramon.nb@gmail.com, thomas.desvenain@gmail.com
